package com.planifai.view;

import com.planifai.model.Evento;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author Marta Rosado Nabais
 */
public class EventoCardTemplate extends javax.swing.JPanel {

    
    public EventoCardTemplate(Evento evento) {
        initComponents();
        configurarEvento(evento);

    }

    /**
     * Configura los datos del evento en la tarjeta.
     *
     * @param evento El objeto Evento del cual se extraerán los detalles para
     * mostrar.
     */
    private void configurarEvento(Evento evento) {
        SimpleDateFormat dayFormat = new SimpleDateFormat("dd", Locale.ENGLISH);
        SimpleDateFormat monthFormat = new SimpleDateFormat("MMM", Locale.ENGLISH);

        // Extraer y formatear la fecha del evento
        String day = dayFormat.format(evento.getFechaEvento());
        String month = monthFormat.format(evento.getFechaEvento()).toUpperCase();

        dayText.setText(day);
        dayText1.setText(month);
        infoText.setText(evento.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        date = new javax.swing.JPanel();
        dayText = new javax.swing.JLabel();
        dayText1 = new javax.swing.JLabel();
        infoText = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(238, 238, 238));

        date.setBackground(new java.awt.Color(246, 128, 93));

        dayText.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        dayText.setForeground(new java.awt.Color(51, 51, 51));
        dayText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayText.setText("30");

        dayText1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        dayText1.setForeground(new java.awt.Color(51, 51, 51));
        dayText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayText1.setText("MAY");

        javax.swing.GroupLayout dateLayout = new javax.swing.GroupLayout(date);
        date.setLayout(dateLayout);
        dateLayout.setHorizontalGroup(
            dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dayText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dayText1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        dateLayout.setVerticalGroup(
            dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayText1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        infoText.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        infoText.setForeground(new java.awt.Color(153, 153, 153));
        infoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoText.setText("Texto sobre el evento en cuestión");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoText, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(infoText))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel date;
    private javax.swing.JLabel dayText;
    private javax.swing.JLabel dayText1;
    private javax.swing.JLabel infoText;
    // End of variables declaration//GEN-END:variables
}
